### ISSUE TITLE
Windows11安装后没有反应， Fatal Python error

### ISSUE THREAD

**Issue by sdlkfjkasdjfkl** [dongyuwei/hallelujahIM#164]
PIME laucher运行正常

版本	Windows 11 家用版
版本	23H2
安装于	‎2023/‎10/‎23
OS 组建	22631.3958
体验	Windows Feature Experience Pack 1000.22700.1026.0

[2024-08-17 16:37:50.288] [PIMELauncher] [error] [Backend error] Exception ignored error evaluating path:
Traceback (most recent call last):
  File "<frozen getpath>", line 490, in <module>
OSError: 
[2024-08-17 16:37:50.288] [PIMELauncher] [error] [Backend error] [Errno 22] Invalid argument
Fatal Python error: error evaluating path
Python runtime state: core initialized

Current thread 0x000051f0 (most recent call first):
  <no Python frame>

**Comment by sdlkfjkasdjfkl** [comment]
Current thread 0x000051f0 (most recent call first):
  <no Python frame>

**Comment by sdlkfjkasdjfkl** [comment]
<no Python frame>

**Comment by sdlkfjkasdjfkl** [comment]
no Python frame

**Comment by sdlkfjkasdjfkl** [comment]
PIME laucher运行正常
Python 3.12.5 

版本 Windows 11 家用版
版本 23H2
安装于 ‎2023/‎10/‎23
OS 组建 22631.3958
体验 Windows Feature Experience Pack 1000.22700.1026.0

[2024-08-17 17:32:49.938] [PIMELauncher] [error] [Backend error] Exception ignored error evaluating path:
Traceback (most recent call last):

[2024-08-17 17:32:49.938] [PIMELauncher] [error] [Backend error]   File "frozen getpath", line 490, in <module>
OSError: [Errno 22] Invalid argument

[2024-08-17 17:32:49.938] [PIMELauncher] [error] [Backend error] Fatal Python error: error evaluating path
Python runtime state: core initialized


[2024-08-17 17:32:49.938] [PIMELauncher] [error] [Backend error] Current thread 0x00005568 (most recent call first):
  no Python frame

**Comment by dongyuwei** [comment]
C:\Users<user>\AppData\Local\PIME\Log
win 11 中可以搜索 %AppData% 快速定位到。看看还有没有其他log日志？如果有的话都贴到这看一下。

上面的log看起来对于定位问题帮助不大。
也可以检查一下C:\Program Files (X86)\PIME 目录下内容是否完整，以及有没有杀毒软件拦截了PIME的启动。

**Comment by sdlkfjkasdjfkl** [comment]
[2024-08-17 18:18:51.283] [PIMELauncher] [debug] SEND: d61b9a8e-ae89-47b6-bef1-72d3c5527238|{"id":"{154ec95a-22dc-412b-9687-1808f91a291f}","isConsole":false,"isMetroApp":true,"isUiLess":false,"isWindows8Above":true,"method":"init","seqNum":106}

**Comment by dongyuwei** [comment]
就这些log吗？
还是没有啥可以debug的

**Comment by sdlkfjkasdjfkl** [comment]
好的，看来要重新安装Window 才能解决，感谢你。

**Comment by dongyuwei** [comment]
我测试开发也是用的windows11。抱歉了
